// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BlazorApp_4.Server;

namespace BlazorApp_4.Server.Data
{
    public partial class Digitalshop_V2Context : DbContext
    {
        public Digitalshop_V2Context()
        {
        }

        public Digitalshop_V2Context(DbContextOptions<Digitalshop_V2Context> options)
            : base(options)
        {
        }

        public virtual DbSet<TblDeviceTypes> TblDeviceTypes { get; set; }
        public virtual DbSet<TblDeviceUsage> TblDeviceUsage { get; set; }
        public virtual DbSet<TblDevices> TblDevices { get; set; }
        public virtual DbSet<TblUsers> TblUsers { get; set; }
        public virtual DbSet<VGetAllDevices> VGetAllDevices { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TblDeviceTypes>(entity =>
            {
                entity.HasKey(e => e.Typeid);

                entity.ToTable("tblDeviceTypes");

                entity.Property(e => e.Typeid).HasColumnName("typeid");

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Shortname)
                    .HasColumnName("shortname")
                    .HasMaxLength(3)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TblDeviceUsage>(entity =>
            {
                entity.ToTable("tblDeviceUsage");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Assigneduserid).HasColumnName("assigneduserid");

                entity.Property(e => e.Deviceid).HasColumnName("deviceid");

                entity.Property(e => e.Endtime)
                    .HasColumnName("endtime")
                    .HasColumnType("date");

                entity.Property(e => e.Historynote)
                    .HasColumnName("historynote")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .HasColumnName("isActive")
                    .HasDefaultValueSql("((0))");

                entity.Property(e => e.Starttime)
                    .HasColumnName("starttime")
                    .HasColumnType("date");
            });

            modelBuilder.Entity<TblDevices>(entity =>
            {
                entity.HasKey(e => e.Deviceid);

                entity.ToTable("tblDevices");

                entity.Property(e => e.Deviceid).HasColumnName("deviceid");

                entity.Property(e => e.IsAvailable).HasColumnName("isAvailable");

                entity.Property(e => e.IsRemoved).HasColumnName("isRemoved");

                entity.Property(e => e.Labelid)
                    .HasColumnName("labelid")
                    .HasMaxLength(10);

                entity.Property(e => e.Macaddress)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Model)
                    .HasColumnName("model")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Price).HasColumnName("price");

                entity.Property(e => e.Purchasedate)
                    .HasColumnName("purchasedate")
                    .HasColumnType("date");

                entity.Property(e => e.Typeid).HasColumnName("typeid");
            });

            modelBuilder.Entity<TblUsers>(entity =>
            {
                entity.HasKey(e => e.UserId)
                    .HasName("PK_tblSiteAdmins");

                entity.ToTable("tblUsers");

                entity.HasIndex(e => e.UserLogin)
                    .HasName("IX_tblUsers")
                    .IsUnique();

                entity.Property(e => e.UserId).HasColumnName("UserID");

                entity.Property(e => e.Avatar).HasMaxLength(255);

                entity.Property(e => e.CanUnCancel).HasDefaultValueSql("((0))");

                entity.Property(e => e.CompanyId).HasColumnName("CompanyID");

                entity.Property(e => e.DefaultAssignTaskTypeId).HasColumnName("DefaultAssignTaskTypeID");

                entity.Property(e => e.DefaultTaskTypeId).HasColumnName("DefaultTaskTypeID");

                entity.Property(e => e.DepartmentId).HasColumnName("DepartmentID");

                entity.Property(e => e.Enabled).HasDefaultValueSql("((1))");

                entity.Property(e => e.GoogleId)
                    .HasColumnName("GoogleID")
                    .HasMaxLength(50);

                entity.Property(e => e.GroupId).HasColumnName("GroupID");

                entity.Property(e => e.HrpersonalId).HasColumnName("HRPersonalId");

                entity.Property(e => e.MyEmail).HasMaxLength(500);

                entity.Property(e => e.NumberCall)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Password).HasMaxLength(50);

                entity.Property(e => e.PhoneNumber).HasMaxLength(250);

                entity.Property(e => e.PhoneUserName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pinnumber)
                    .HasColumnName("PINNumber")
                    .HasMaxLength(6);

                entity.Property(e => e.PositionId).HasColumnName("PositionID");

                entity.Property(e => e.ReceiveNewTasks).HasDefaultValueSql("((1))");

                entity.Property(e => e.RoleId).HasColumnName("roleID");

                entity.Property(e => e.SendRepeatMessages).HasDefaultValueSql("((0))");

                entity.Property(e => e.SimpleKrmview).HasColumnName("SimpleKRMView");

                entity.Property(e => e.SubDepartmentId).HasColumnName("SubDepartmentID");

                entity.Property(e => e.TokenExpired).HasColumnType("datetime");

                entity.Property(e => e.TokenValue).HasMaxLength(10);

                entity.Property(e => e.UserAuth).HasDefaultValueSql("((10))");

                entity.Property(e => e.UserLogin)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.UserPassword)
                    .IsRequired()
                    .HasMaxLength(30);

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.ViewStats).HasDefaultValueSql("((0))");

                entity.Property(e => e.WarehouseLocationId).HasColumnName("WarehouseLocationID");
            });

            modelBuilder.Entity<VGetAllDevices>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vGetAllDevices");

                entity.Property(e => e.Deviceid).HasColumnName("deviceid");

                entity.Property(e => e.IsAvailable).HasColumnName("isAvailable");

                entity.Property(e => e.IsRemoved).HasColumnName("isRemoved");

                entity.Property(e => e.Labelid)
                    .HasColumnName("labelid")
                    .HasMaxLength(10);

                entity.Property(e => e.Macaddress)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Model)
                    .HasColumnName("model")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Name)
                    .HasColumnName("name")
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.Price).HasColumnName("price");

                entity.Property(e => e.Purchasedate)
                    .HasColumnName("purchasedate")
                    .HasColumnType("date");

                entity.Property(e => e.Typeid).HasColumnName("typeid");

                entity.Property(e => e.Typename)
                    .HasColumnName("typename")
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}