// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorApp_4.Server
{
    public partial class TblDeviceTypes
    {
        public int Typeid { get; set; }
        public string Name { get; set; }
        public string Shortname { get; set; }
    }
}