// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorApp_4.Server
{
    public partial class TblDeviceUsage
    {
        public int Id { get; set; }
        public int? Deviceid { get; set; }
        public int? Assigneduserid { get; set; }
        public DateTime? Starttime { get; set; }
        public DateTime? Endtime { get; set; }
        public string Historynote { get; set; }
        public bool? IsActive { get; set; }
    }
}