// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorApp_4.Server
{
    public partial class TblUsers
    {
        public int UserId { get; set; }
        public int CompanyId { get; set; }
        public string Username { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int UserAuth { get; set; }
        public int? PositionId { get; set; }
        public string Avatar { get; set; }
        public string MyEmail { get; set; }
        public int? Active { get; set; }
        public int? DepartmentId { get; set; }
        public string GoogleId { get; set; }
        public int? RoleId { get; set; }
        public bool? PasswordNeverExpired { get; set; }
        public int? HrpersonalId { get; set; }
        public bool? Manager { get; set; }
        public bool? ReceiveNewTasks { get; set; }
        public bool? ViewStats { get; set; }
        public bool? Enabled { get; set; }
        public bool? FtpAccess { get; set; }
        public bool? CanRefund { get; set; }
        public bool? AdvancedStats { get; set; }
        public bool? SimpleKrmview { get; set; }
        public bool? CanUnCancel { get; set; }
        public bool? SendRepeatMessages { get; set; }
        public bool? WantsCalls { get; set; }
        public string PhoneUserName { get; set; }
        public int? GroupId { get; set; }
        public int? DefaultTaskTypeId { get; set; }
        public string NumberCall { get; set; }
        public string Pinnumber { get; set; }
        public string TokenValue { get; set; }
        public DateTime? TokenExpired { get; set; }
        public int? DefaultAssignTaskTypeId { get; set; }
        public string PhoneNumber { get; set; }
        public bool? ChangePassEspresso { get; set; }
        public bool? CanNotAssign { get; set; }
        public string Password { get; set; }
        public int? WarehouseLocationId { get; set; }
        public bool? IsGatehouse { get; set; }
        public int? SubDepartmentId { get; set; }
    }
}