// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace BlazorApp_4.Server
{
    public partial class VGetAllDevices
    {
        public int Deviceid { get; set; }
        public string Labelid { get; set; }
        public int? Typeid { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public DateTime? Purchasedate { get; set; }
        public bool? IsAvailable { get; set; }
        public bool? IsRemoved { get; set; }
        public string Typename { get; set; }
        public string Macaddress { get; set; }
        public double? Price { get; set; }
    }
}